### ISSUE TITLE
The left navigation bar is truncated on lower display resolutions like 1280x800 or 2560x1600 with scale of 200%

### ISSUE THREAD

**Issue by lyveng** [monitoring-mixins/website#19]
**Browser**: 
1. Firefox 78.6.1esr (64-bit)
2. Chrome 87.0.4280.88

**OS** - Debian 10

All entries below prometheus-operator on the left navigation bar are not accessible even if we try to scroll.

**Comment by v-zhuravlev** [comment]
Should be fixed by https://github.com/monitoring-mixins/website/pull/45
