### ISSUE TITLE
Cortex appears outdated

### ISSUE THREAD

**Issue by jessequinn** [monitoring-mixins/website#31]
Not sure if it is just me, but many of the metrics the Cortex Dashboards use are non-existent today.

**Comment by v-zhuravlev** [comment]
Cortex was  updated  few weeks ago: https://github.com/monitoring-mixins/website/commit/6825ac3a6f83f06b1e9f169d82b03b90cbab2a49#diff-b26c1b5b189f0f3cee5a06b5baeb85200abe265f0ec73d7a235bfe13d39e0332

Hope it helps.
