### ISSUE TITLE
prometheus-remote-write dashboard not importable in grafana

### ISSUE THREAD

**Issue by g-bohncke** [monitoring-mixins/website#33]
the [prometheus-remote-write dashboard](https://github.com/monitoring-mixins/website/blob/master/assets/prometheus/dashboards/prometheus-remote-write.json) fails to load in Grafana. with the following error:

Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Btype%2C%20uid%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

changing
"current": {
   "text": {
      "selected": true,
      "text": "All",
      "value": "$__all"
   },
   "value": {
      "selected": true,
      "text": "All",
      "value": "$__all"
   }
},

to: makes it work again:

"current": {
  "selected": true,
  "text": "All",
  "value": "$__all"
}

**Comment by v-zhuravlev** [comment]
Successfully imported the latest dashboard [prometheus-remote-write dashboard](https://github.com/monitoring-mixins/website/blob/master/assets/prometheus/dashboards/prometheus-remote-write.json) that had been updated 2 weeks ago to Grafana 11.3.
