### ISSUE TITLE
A number of dashboards including Thanos Compact and Thanos Query are using depreciated Graph Old plugin 

### ISSUE THREAD

**Issue by sossickd** [monitoring-mixins/website#35]
A number of dashboards including [Thanos Compact](https://github.com/monitoring-mixins/website/blob/master/assets/thanos/dashboards/compact.json) and [Thanos Query](https://github.com/monitoring-mixins/website/blob/master/assets/thanos/dashboards/query.json) are using depreciated Graph Old plugin.

![image](https://github.com/monitoring-mixins/website/assets/16937121/4a16e2e4-7cae-4a00-bf5a-d2b301354cfb)

Angular support will be removed in in version 11, which will be released in 2024.

https://grafana.com/docs/grafana/latest/developers/angular_deprecation/

Is there a plan to mitigate this depreciation on dashboards using Graph (old) in the near future?

There are alternative plugins such as Time Series, Bar chart etc

**Comment by sossickd** [comment]
Might be worth adding an alerts panel at the top and a Loki pal at the bottom with log levels and a quotable panel based on severity. Sorry need to learn jsonnet

**Comment by v-zhuravlev** [comment]
I think those dashboards should be updated in Thanos repo. Once updated there, dashboards would be automatically updated here as well :)

**Comment by aditya-konarde** [comment]
Likely related: https://github.com/thanos-io/thanos/issues/7413
