### ISSUE TITLE
cert-manager last commit breaks all legends

### ISSUE THREAD

**Issue by sherif-fanous** [monitoring-mixins/website#37]
The value of all `legendFormat` keys in the latest commit are invalid as there are spaces between the braces

**Example**

https://github.com/monitoring-mixins/website/blob/b731a997db12f62dc1cab953fb97f7b867c35ecd/assets/cert-manager/dashboards/cert-manager.json#L123C16-L123C51

```json
"legendFormat": "{ {condition } }",
```

should be

```json
"legendFormat": "{{condition}}",
```

**Comment by haraldkoch** [comment]
I just tripped over this myself.

**Comment by christfriedbalizou** [comment]
This PR should fix it https://github.com/monitoring-mixins/website/pull/42/files. Also, this issue seems old. unfortunately, I suspect people just create their own files.

**Comment by v-zhuravlev** [comment]
Hi, this issue is not present in the latest version: https://github.com/monitoring-mixins/website/blob/master/assets/cert-manager/dashboards/overview.json
