### ISSUE TITLE
Sidebar doesn't scroll

### ISSUE THREAD

**Issue by RiRa12621** [monitoring-mixins/website#44]
The sidebar is just stuck the way it is, resulting in `envoy` being the last readable option for me
<img width="1033" alt="Screenshot 2024-11-06 at 17 54 01" src="https://github.com/user-attachments/assets/f6fbbf3a-ab29-426c-960e-cb6af9fee86a">

Chrome Version 130.0.6723.71 
MacOS 14.6.1 (23G93)

**Comment by adamhackl** [comment]
+1
